2019-08-24 18:06:16,184 [ERROR]  Task exception was never retrieved
future: <Task finished coro=<SanicPluginsFramework._handle_request() done, defined at c:\users\nizam\appdata\local\programs\python\python36\lib\site-packages\spf\framework.py:471> exception=SystemExit(0,)>
Traceback (most recent call last):
  File "c:\users\nizam\appdata\local\programs\python\python36\lib\site-packages\rasa\cli\x.py", line 322, in run_locally
    local.main(args, project_path, args.data, token=rasa_x_token)
  File "c:\users\nizam\appdata\local\programs\python\python36\lib\site-packages\rasax\community\local.py", line 220, in main
    access_log=False,
  File "c:\users\nizam\appdata\local\programs\python\python36\lib\site-packages\sanic\app.py", line 1096, in run
    serve(**server_settings)
  File "c:\users\nizam\appdata\local\programs\python\python36\lib\site-packages\sanic\server.py", line 770, in serve
    loop.run_forever()
  File "c:\users\nizam\appdata\local\programs\python\python36\lib\asyncio\base_events.py", line 438, in run_forever
    self._run_once()
  File "c:\users\nizam\appdata\local\programs\python\python36\lib\asyncio\base_events.py", line 1451, in _run_once
    handle._run()
  File "c:\users\nizam\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\nizam\appdata\local\programs\python\python36\lib\site-packages\spf\framework.py", line 476, in _handle_request
    stream_callback)
  File "c:\users\nizam\appdata\local\programs\python\python36\lib\site-packages\sanic\app.py", line 917, in handle_request
    response = await response
  File "c:\users\nizam\appdata\local\programs\python\python36\lib\site-packages\rasax\community\api\decorators.py", line 179, in decorated_function
    return await await_and_return_response(args, kwargs, request)
  File "c:\users\nizam\appdata\local\programs\python\python36\lib\site-packages\rasax\community\api\decorators.py", line 109, in await_and_return_response
    response = await response
  File "c:\users\nizam\appdata\local\programs\python\python36\lib\site-packages\rasax\community\api\blueprints\models.py", line 32, in get_models
    project_id, limit, offset
  File "c:\users\nizam\appdata\local\programs\python\python36\lib\site-packages\rasax\community\services\model_service.py", line 479, in get_models
    await self._discover_models()
  File "c:\users\nizam\appdata\local\programs\python\python36\lib\site-packages\rasax\community\services\model_service.py", line 94, in _discover_models
    model_version = self.get_model_version(path)
  File "c:\users\nizam\appdata\local\programs\python\python36\lib\site-packages\rasax\community\services\model_service.py", line 441, in get_model_version
    metadata = self.get_model_metadata(file_path)
  File "c:\users\nizam\appdata\local\programs\python\python36\lib\site-packages\rasax\community\services\model_service.py", line 428, in get_model_metadata
    tar.extractall(tdir)
  File "c:\users\nizam\appdata\local\programs\python\python36\lib\tarfile.py", line 2010, in extractall
    numeric_owner=numeric_owner)
  File "c:\users\nizam\appdata\local\programs\python\python36\lib\tarfile.py", line 2052, in extract
    numeric_owner=numeric_owner)
  File "c:\users\nizam\appdata\local\programs\python\python36\lib\tarfile.py", line 2122, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "c:\users\nizam\appdata\local\programs\python\python36\lib\tarfile.py", line 2163, in makefile
    with bltn_open(targetpath, "wb") as target:
  File "c:\users\nizam\appdata\local\programs\python\python36\lib\site-packages\rasa\cli\utils.py", line 192, in signal_handler
    sys.exit(0)
SystemExit: 0
